# -*- coding: utf-8 -*-
"""Sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2ehMQ62DDVf01NDCIKbMK-1Q3EQlk00
"""

from textblob import TextBlob

def analyze(text):
  blob = TextBlob(text)
  pol = blob.sentiment.polarity
  if pol > 0:
    return "Positive"
  elif pol < 0:
    return "Negative"
  else:
    return "Neutral"

def main():
  while True:
    s = input("Enter a text (type exit to quit): ")
    if s.lower()=='exit':
      break
    sent = analyze(s)
    print(f"Sentiment for the given sentence is = {sent}\n")
if __name__ == "__main__":
  main()